<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Jellyfin.Plugin.MediaFlow</RootNamespace>
    <AssemblyName>Jellyfin.Plugin.MediaFlow</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Jellyfin.Controller" Version="$(JellyfinVersion)">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Jellyfin.Model" Version="$(JellyfinVersion)">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Remove="Configuration/configPage.html" />
    <EmbeddedResource Include="Configuration/configPage.html" />
    <None Remove="Localization/*.json" />
    <EmbeddedResource Include="Localization/*.json" />
  </ItemGroup>
</Project>
